/-
Copyright (c) 2026. All rights reserved.
Author: julian1c2a
License: MIT
-/

-- Root module: auto-generated by gen-root.bash
-- Uses barrel imports for subdirectories (see AI-GUIDE.md §17-18).
-- Run 'bash gen-root.bash' after adding or removing modules.

import PeanoRF.Prelim
import PeanoRF.HA.Arith
import PeanoRF.HA.Axioms
import PeanoRF.Meta.AxiomCheck
import PeanoRF.Omega.Basic
