/-
Copyright (c) 2026. All rights reserved.
Author: julian1c2a
License: MIT
-/

-- Root module: auto-generated by gen-root.bash
-- Uses barrel imports for subdirectories (see AI-GUIDE.md §17-18).
-- Run 'bash gen-root.bash' after adding or removing modules.

import PeanoRF.Prelim
import PeanoRF.Calculus.Collapse
import PeanoRF.Calculus.Consistency
import PeanoRF.Calculus.DerivesI
import PeanoRF.Calculus.Eq
import PeanoRF.Calculus.Slash
import PeanoRF.Calculus.Soundness
import PeanoRF.Calculus.Subst
import PeanoRF.Calculus.SubstDerives
import PeanoRF.HA.Arith
import PeanoRF.HA.Axioms
import PeanoRF.HA.Domain
import PeanoRF.HA.Fragment
import PeanoRF.HA.Model
import PeanoRF.HA.Numerals
import PeanoRF.HA.Order
import PeanoRF.HA.SlashAxioms
import PeanoRF.Meta.AxiomCheck
import PeanoRF.Omega.Basic
